#include "lexer.h"
#include <ctype.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#define C_RED "\033[31m"
#define C_YELLOW "\033[33m"
#define C_CYAN "\033[36m"
#define C_DIM "\033[2m"
#define C_RESET "\033[0m"
static void lexer_error(int line,int column,const char *code,const char *message,const char *detail){
    fprintf(stderr,C_RED "I found a problem in your source" C_RESET " " C_DIM "[%s]" C_RESET " at %d:%d\n",code,line,column);
    fprintf(stderr,"  " C_YELLOW "%s" C_RESET, message);
    if(detail&&*detail)fprintf(stderr,"\n  " C_CYAN "Suggestion:" C_RESET " %s",detail);
    fputc('\n',stderr);
}
static char*dup_range(const char*a,const char*b){size_t n=(size_t)(b-a);char*s=malloc(n+1);if(!s)return NULL;memcpy(s,a,n);s[n]=0;return s;}
static void push(TokenList*l,Token t){if(l->count==l->capacity){size_t c=l->capacity?l->capacity*2:64;Token*p=realloc(l->items,c*sizeof(*p));if(!p)exit(2);l->items=p;l->capacity=c;}l->items[l->count++]=t;}
static TokenType kw(const char*s){if(!strcmp(s,"define"))return TOK_DEFINE;if(!strcmp(s,"if"))return TOK_IF;if(!strcmp(s,"else"))return TOK_ELSE;if(!strcmp(s,"for"))return TOK_FOR;if(!strcmp(s,"in"))return TOK_IN;if(!strcmp(s,"while"))return TOK_WHILE;if(!strcmp(s,"func"))return TOK_FUNC;if(!strcmp(s,"return"))return TOK_RETURN;if(!strcmp(s,"break"))return TOK_BREAK;if(!strcmp(s,"continue"))return TOK_CONTINUE;if(!strcmp(s,"import"))return TOK_IMPORT;if(!strcmp(s,"from"))return TOK_FROM;if(!strcmp(s,"true"))return TOK_TRUE;if(!strcmp(s,"false"))return TOK_FALSE;if(!strcmp(s,"null"))return TOK_NULL;return TOK_IDENTIFIER;}
TokenList lex_source(const char*src){TokenList o={0};const char*p=src;int line=1,col=1;while(*p){if(*p==' '||*p=='\t'||*p=='\r'){p++;col++;continue;}if(*p=='\n'){p++;line++;col=1;continue;}if(*p=='#'){while(*p&&*p!='\n'){p++;col++;}continue;}if(isalpha((unsigned char)*p)||*p=='_'){const char*a=p;int c=col;while(isalnum((unsigned char)*p)||*p=='_'){p++;col++;}char*s=dup_range(a,p);push(&o,(Token){kw(s),s,0,line,c});continue;}if(isdigit((unsigned char)*p)||(*p=='.'&&isdigit((unsigned char)p[1]))){const char*a=p;int c=col;char*e;double n=strtod(p,&e);while(p<e){p++;col++;}push(&o,(Token){TOK_NUMBER,dup_range(a,p),n,line,c});continue;}if(*p=='"'||*p=='\''){char q=*p++;col++;int l=line,c=col;size_t cap=32,n=0;char*s=malloc(cap);if(!s)exit(2);while(*p&&*p!=q){char ch=*p++;col++;if(ch=='\\'&&*p){char e=*p++;col++;ch=e=='n'?'\n':e=='r'?'\r':e=='t'?'\t':e=='\\'?'\\':e=='"'?'"':e=='\''?'\'':e;}if(n+1>=cap){cap*=2;s=realloc(s,cap);}s[n++]=ch;}if(*p==q){p++;col++;}else{lexer_error(l,c,"LEX002","unterminated string","expected a closing quote");free(s);push(&o,(Token){TOK_ERROR,strdup("unterminated string"),0,l,c});break;}s[n]=0;push(&o,(Token){TOK_STRING,s,0,l,c});continue;}TokenType t=TOK_ERROR;int n=1;switch(*p){case'(':t=TOK_LPAREN;break;case')':t=TOK_RPAREN;break;case'{':t=TOK_LBRACE;break;case'}':t=TOK_RBRACE;break;case'[':t=TOK_LBRACKET;break;case']':t=TOK_RBRACKET;break;case',':t=TOK_COMMA;break;case'.':t=TOK_DOT;break;case':':t=TOK_COLON;break;case';':t=TOK_SEMICOLON;break;case'+':t=TOK_PLUS;break;case'-':t=TOK_MINUS;break;case'*':t=TOK_STAR;break;case'/':t=TOK_SLASH;break;case'%':t=TOK_PERCENT;break;case'!':if(p[1]=='='){t=TOK_BANG_EQUAL;n=2;}else t=TOK_BANG;break;case'=':if(p[1]=='='){t=TOK_EQUAL_EQUAL;n=2;}else t=TOK_EQUAL;break;case'<':if(p[1]=='='){t=TOK_LESS_EQUAL;n=2;}else t=TOK_LESS;break;case'>':if(p[1]=='='){t=TOK_GREATER_EQUAL;n=2;}else t=TOK_GREATER;break;case'&':if(p[1]=='&'){t=TOK_AND_AND;n=2;}break;case'|':if(p[1]=='|'){t=TOK_OR_OR;n=2;}break;}if(t==TOK_ERROR){char*m=malloc(128);if(!m)exit(2);snprintf(m,128,"unexpected character '%c'",*p);lexer_error(line,col,"LEX001","unexpected character",m);push(&o,(Token){t,m,0,line,col});p++;col++;}else{push(&o,(Token){t,dup_range(p,p+n),0,line,col});p+=n;col+=n;}}push(&o,(Token){TOK_EOF,strdup(""),0,line,col});return o;}
void free_tokens(TokenList*t){for(size_t i=0;i<t->count;i++)free(t->items[i].lexeme);free(t->items);*t=(TokenList){0};}
const char*token_type_name(TokenType t){switch(t){case TOK_EOF:return"EOF";case TOK_ERROR:return"ERROR";case TOK_IDENTIFIER:return"identifier";case TOK_NUMBER:return"number";case TOK_STRING:return"string";case TOK_DEFINE:return"define";case TOK_IF:return"if";case TOK_ELSE:return"else";case TOK_FOR:return"for";case TOK_IN:return"in";case TOK_WHILE:return"while";case TOK_FUNC:return"func";case TOK_RETURN:return"return";case TOK_BREAK:return"break";case TOK_CONTINUE:return"continue";case TOK_IMPORT:return"import";case TOK_FROM:return"from";case TOK_TRUE:return"true";case TOK_FALSE:return"false";case TOK_NULL:return"null";default:return"symbol";}}
