#include "value.h"
#include "bytecode.h"
#include "lexer.h"
#include <math.h>
#include <stdlib.h>
#include <string.h>
static char*sd(const char*s){char*p=strdup(s?s:"");if(!p)exit(2);return p;}
const char*gs_type_name(GSValueType t){switch(t){case V_NULL:return "null";case V_NUMBER:return "number";case V_BOOL:return "bool";case V_STRING:return "string";case V_ARRAY:return "array";case V_OBJECT:return "object";case V_FUNCTION:return "function";case V_NATIVE:return "native function";case V_ITER:return "iterator";default:return "unknown";}}
GSValue gs_null(void){return(GSValue){.type=V_NULL};}
GSValue gs_number(double n){return(GSValue){.type=V_NUMBER,.as.number=n};}
GSValue gs_bool(int b){return(GSValue){.type=V_BOOL,.as.boolean=!!b};}
GSValue gs_string(const char*s){GSValue v={.type=V_STRING};v.as.string.data=sd(s);v.as.string.refs=1;return v;}
GSValue gs_array(void){GSValue v={.type=V_ARRAY};v.as.array=calloc(1,sizeof*v.as.array);if(!v.as.array)exit(2);v.as.array->refs=1;return v;}
GSValue gs_object(void){GSValue v={.type=V_OBJECT};v.as.object=calloc(1,sizeof*v.as.object);if(!v.as.object)exit(2);v.as.object->refs=1;return v;}
GSValue gs_native(GSNativeFn f){return(GSValue){.type=V_NATIVE,.as.native=f};}
GSValue gs_iterator(GSValue v){GSValue x={.type=V_ITER};x.as.iter=calloc(1,sizeof*x.as.iter);if(!x.as.iter)exit(2);x.as.iter->refs=1;x.as.iter->iterable=gs_copy(v);return x;}
GSValue gs_function(GSCode*c,GSEnvironment*e){GSValue v={.type=V_FUNCTION};v.as.function.code=c;v.as.function.closure=e;code_retain(c);env_retain(e);return v;}
void gs_retain(GSValue v){switch(v.type){case V_STRING:break;case V_ARRAY:v.as.array->refs++;break;case V_OBJECT:v.as.object->refs++;break;case V_FUNCTION:code_retain(v.as.function.code);env_retain(v.as.function.closure);break;case V_ITER:v.as.iter->refs++;break;default:break;}}
void gs_release(GSValue v){switch(v.type){case V_STRING:break;case V_ARRAY:if(--v.as.array->refs==0){for(size_t i=0;i<v.as.array->count;i++)gs_release(v.as.array->items[i]);free(v.as.array->items);free(v.as.array);}break;case V_OBJECT:if(--v.as.object->refs==0){for(size_t i=0;i<v.as.object->count;i++){free(v.as.object->items[i].key);gs_release(v.as.object->items[i].value);}free(v.as.object->items);free(v.as.object);}break;case V_FUNCTION:code_release(v.as.function.code);env_release(v.as.function.closure);break;case V_ITER:if(--v.as.iter->refs==0){gs_release(v.as.iter->iterable);free(v.as.iter);}break;default:break;}}
GSValue gs_copy(GSValue v){gs_retain(v);return v;}
void gs_array_push(GSValue*a,GSValue v){if(!a||a->type!=V_ARRAY)return;GSArray*x=a->as.array;if(x->count==x->capacity){size_t c=x->capacity?x->capacity*2:8;x->items=realloc(x->items,c*sizeof*x->items);if(!x->items)exit(2);x->capacity=c;}x->items[x->count++]=gs_copy(v);}
size_t gs_array_count(GSValue v){return v.type==V_ARRAY?v.as.array->count:0;}
GSValue gs_array_get(GSValue v,size_t index){if(v.type!=V_ARRAY||index>=v.as.array->count)return gs_null();return gs_copy(v.as.array->items[index]);}
int gs_array_set(GSValue*v,size_t index,GSValue value){if(!v||v->type!=V_ARRAY)return 0;while(index>=v->as.array->count)gs_array_push(v,gs_null());gs_release(v->as.array->items[index]);v->as.array->items[index]=gs_copy(value);return 1;}
GSValue gs_index(GSValue o,GSValue i){if(o.type==V_ARRAY){long n=(long)gs_number_value(i);if(n>=0&&(size_t)n<o.as.array->count)return gs_copy(o.as.array->items[n]);}if(o.type==V_STRING){long n=(long)gs_number_value(i);size_t z=strlen(o.as.string.data);if(n>=0&&(size_t)n<z){char b[2]={o.as.string.data[n],0};return gs_string(b);}}if(o.type==V_OBJECT)return gs_object_get(o,gs_cstring(i));return gs_null();}
int gs_set_index(GSValue o,GSValue i,GSValue v){if(o.type==V_ARRAY){long n=(long)gs_number_value(i);if(n<0)return 0;while((size_t)n>=o.as.array->count)gs_array_push(&o,gs_null());gs_release(o.as.array->items[n]);o.as.array->items[n]=gs_copy(v);return 1;}if(o.type==V_OBJECT){gs_object_set(&o,gs_cstring(i),v);return 1;}return 0;}
void gs_object_set(GSValue*o,const char*k,GSValue v){if(!o||o->type!=V_OBJECT||!k)return;GSObject*x=o->as.object;for(size_t i=0;i<x->count;i++)if(!strcmp(x->items[i].key,k)){gs_release(x->items[i].value);x->items[i].value=gs_copy(v);return;}if(x->count==x->capacity){size_t c=x->capacity?x->capacity*2:8;x->items=realloc(x->items,c*sizeof*x->items);if(!x->items)exit(2);x->capacity=c;}x->items[x->count].key=sd(k);x->items[x->count++].value=gs_copy(v);}
GSValue gs_object_get(GSValue o,const char*k){if(o.type!=V_OBJECT||!k)return gs_null();for(size_t i=0;i<o.as.object->count;i++)if(!strcmp(o.as.object->items[i].key,k))return gs_copy(o.as.object->items[i].value);return gs_null();}
size_t gs_object_count(GSValue v){return v.type==V_OBJECT?v.as.object->count:0;}
const char*gs_object_key(GSValue v,size_t index){if(v.type!=V_OBJECT||index>=v.as.object->count)return NULL;return v.as.object->items[index].key;}
GSEnvironment*env_new(GSEnvironment*p){GSEnvironment*e=calloc(1,sizeof*e);if(!e)exit(2);e->refs=1;e->parent=p;if(p)env_retain(p);return e;}
void env_retain(GSEnvironment*e){if(e)e->refs++;}
void env_release(GSEnvironment*e){if(!e||--e->refs)return;GSEnvironment*p=e->parent;for(GSBinding*b=e->bindings;b;){GSBinding*n=b->next;free(b->name);gs_release(b->value);free(b);b=n;}free(e);env_release(p);}
void env_define(GSEnvironment*e,const char*n,GSValue v){GSBinding*b=calloc(1,sizeof*b);if(!b)exit(2);b->name=sd(n);b->value=gs_copy(v);b->next=e->bindings;e->bindings=b;}
int env_set(GSEnvironment*e,const char*n,GSValue v){for(GSEnvironment*x=e;x;x=x->parent)for(GSBinding*b=x->bindings;b;b=b->next)if(!strcmp(b->name,n)){gs_release(b->value);b->value=gs_copy(v);return 1;}return 0;}
int env_get(GSEnvironment*e,const char*n,GSValue*out){for(GSEnvironment*x=e;x;x=x->parent)for(GSBinding*b=x->bindings;b;b=b->next)if(!strcmp(b->name,n)){*out=gs_copy(b->value);return 1;}return 0;}
int gs_truthy(GSValue v){switch(v.type){case V_NULL:return 0;case V_BOOL:return v.as.boolean;case V_NUMBER:return v.as.number!=0;case V_STRING:return v.as.string.data[0]!=0;case V_ARRAY:return v.as.array->count!=0;case V_OBJECT:return v.as.object->count!=0;default:return 1;}}
double gs_number_value(GSValue v){if(v.type==V_NUMBER)return v.as.number;if(v.type==V_BOOL)return v.as.boolean;if(v.type==V_STRING)return strtod(v.as.string.data,NULL);return 0;}
const char*gs_cstring(GSValue v){static char buf[128];switch(v.type){case V_STRING:return v.as.string.data;case V_NULL:return"null";case V_BOOL:return v.as.boolean?"true":"false";case V_NUMBER:snprintf(buf,sizeof buf,"%.15g",v.as.number);return buf;case V_ARRAY:return"[array]";case V_OBJECT:return"[object]";case V_FUNCTION:return"[function]";case V_NATIVE:return"[native function]";case V_ITER:return"[iterator]";}return"null";}
void gs_print(FILE*f,GSValue v){switch(v.type){case V_ARRAY:fputc('[',f);for(size_t i=0;i<v.as.array->count;i++){if(i)fputs(", ",f);gs_print(f,v.as.array->items[i]);}fputc(']',f);break;case V_OBJECT:fputc('{',f);for(size_t i=0;i<v.as.object->count;i++){if(i)fputs(", ",f);fprintf(f,"%s: ",v.as.object->items[i].key);gs_print(f,v.as.object->items[i].value);}fputc('}',f);break;default:fputs(gs_cstring(v),f);}}
int gs_equal(GSValue a,GSValue b){if((a.type==V_NUMBER&&b.type==V_BOOL)||(a.type==V_BOOL&&b.type==V_NUMBER))return gs_number_value(a)==gs_number_value(b);if(a.type!=b.type)return 0;switch(a.type){case V_NULL:return 1;case V_NUMBER:return a.as.number==b.as.number;case V_BOOL:return a.as.boolean==b.as.boolean;case V_STRING:return!strcmp(a.as.string.data,b.as.string.data);case V_ARRAY:return a.as.array==b.as.array;case V_OBJECT:return a.as.object==b.as.object;case V_ITER:return a.as.iter==b.as.iter;default:return a.as.function.code==b.as.function.code&&a.as.function.closure==b.as.function.closure;}}
GSValue gs_binary(int op,GSValue a,GSValue b){if(op==TOK_EQUAL_EQUAL)return gs_bool(gs_equal(a,b));if(op==TOK_BANG_EQUAL)return gs_bool(!gs_equal(a,b));if(op==TOK_LESS)return gs_bool(gs_number_value(a)<gs_number_value(b));if(op==TOK_LESS_EQUAL)return gs_bool(gs_number_value(a)<=gs_number_value(b));if(op==TOK_GREATER)return gs_bool(gs_number_value(a)>gs_number_value(b));if(op==TOK_GREATER_EQUAL)return gs_bool(gs_number_value(a)>=gs_number_value(b));if(op==TOK_PLUS&&(a.type==V_STRING||b.type==V_STRING)){const char*x=gs_cstring(a),*y=gs_cstring(b);size_t n=strlen(x)+strlen(y)+1;char*s=malloc(n);if(!s)exit(2);snprintf(s,n,"%s%s",x,y);GSValue v={.type=V_STRING,.as.string={s,1}};return v;}double x=gs_number_value(a),y=gs_number_value(b);switch(op){case TOK_PLUS:return gs_number(x+y);case TOK_MINUS:return gs_number(x-y);case TOK_STAR:return gs_number(x*y);case TOK_SLASH:return y==0?gs_null():gs_number(x/y);case TOK_PERCENT:return y==0?gs_null():gs_number(fmod(x,y));default:return gs_null();}}
